name: Documentation

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.23.0
        environments: doc
        frozen: true

    - name: Build documentation
      run: pixi run -e doc build-doc

    - name: Update the main gh-page website
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/_build/html
        commit_message: "[ci skip] ${{ github.event.head_commit.message }}"
